"""Static policy and loop settings for the toy application."""

from decimal import Decimal
from typing import Final

REFUND_APPROVAL_THRESHOLD: Final = Decimal("500.00")
APPROVAL_TTL_SECONDS: Final = 900
VERIFICATION_TTL_SECONDS: Final = 900
MAX_AGENT_STEPS: Final = 12
MAX_INVALID_OUTPUTS: Final = 3
MODEL_CALL_TIMEOUT_SECONDS: Final = 30.0
MODEL_RESPONSE_MAX_BYTES: Final = 65_536
MODEL_WORKER_WALL_CLOCK_SECONDS: Final = MODEL_CALL_TIMEOUT_SECONDS
MODEL_WORKER_CPU_SECONDS: Final = 5
MODEL_WORKER_MEMORY_BYTES: Final = 128 * 1024 * 1024
MODEL_WORKER_MAX_REQUEST_BYTES: Final = 512 * 1024
DENIAL_LOOP_THRESHOLD: Final = 3
VERIFICATION_SUBJECT: Final = "Verify your email address"
VERIFICATION_BODY: Final = "Use this verification token to continue: {token}"
UNKNOWN_SENDER_SUBJECT: Final = "We could not find your account"
UNKNOWN_SENDER_BODY: Final = (
    "Please contact support using the email address on your account."
)

HTTP_ENVELOPE_FROM_MAX_LENGTH: Final = 320
HTTP_MESSAGE_ID_MAX_LENGTH: Final = 998
HTTP_INBOUND_SUBJECT_MAX_LENGTH: Final = 998
HTTP_INBOUND_BODY_MAX_LENGTH: Final = 100_000
HTTP_REFUND_ID_MAX_LENGTH: Final = 64
HTTP_OPERATOR_ID_MAX_LENGTH: Final = 128
HTTP_OPERATOR_REASON_MAX_LENGTH: Final = 2_000
HTTP_VERIFICATION_TOKEN_MAX_LENGTH: Final = 256

ACTION_TEXT_FIELD_MAX_LENGTH: Final = 4_000
ACTION_ORDER_ID_MAX_LENGTH: Final = 64

INVALID_OUTPUT_PREVIEW_MAX_BYTES: Final = 4_096

PROMPT_UNTRUSTED_FIELD_MAX_CHARS: Final = 2_000
PROMPT_MEMORY_SERIALIZED_MAX_BYTES: Final = 65_536
PROMPT_TOTAL_MAX_BYTES: Final = 131_072
AUTHORIZED_ORDER_COUNT_MAX: Final = 100
